#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
   
   
    arr = []
    s1 = str(bin(n))[2:]
    for i in range(1,len(s1)):
        count = 0
        for i1 in range(i,-1,-1):
            if  s1[i1] == '1':
                if (s1[i1] == s1[i]):
                    count+=1
                else:
                    count =1
                    break
            else:
                break 
                  
        arr.append(count)

    print(max(arr))
