#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())
    
    if N % 2 == 0:
        if (N >= 2 & N <= 5) | N > 20:
            print('Not Weird')   
        else:
            if (N >= 6 & N <= 20):
                print('Weird')        
    else:
        print('Weird')
        
